# Generated by Django 4.2.7 on 2023-11-21 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(default="None", max_length=255)),
                (
                    "department",
                    models.CharField(default="Транспортный участок", max_length=255),
                ),
                (
                    "position",
                    models.CharField(default="Водитель погрузчика", max_length=255),
                ),
                ("quality", models.CharField(default="3 разряд", max_length=255)),
                ("birth_date", models.DateField(default="None")),
                ("age", models.IntegerField(default="18")),
                ("male", models.CharField(default="М", max_length=10)),
                ("education", models.CharField(default="None", max_length=255)),
                ("experience", models.IntegerField(default=2)),
                ("extra", models.FloatField(default=0.02)),
                ("address", models.CharField(default="None", max_length=255)),
                ("instruction_date", models.DateField()),
                (
                    "instruction_type",
                    models.CharField(
                        choices=[
                            ("primary", "Первичный"),
                            ("recurring", "Повторный"),
                            ("ad_hoc", "Внеплановый"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkClothes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                ("issue_date", models.DateField()),
                ("expiry_date", models.DateField()),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Training",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("training_type", models.CharField(max_length=200)),
                ("last_training_date", models.DateField()),
                ("next_training_date", models.DateField()),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.employee",
                    ),
                ),
            ],
        ),
    ]
